name: Devops-github-pipeline

on:
  workflow_dispatch:

env:
  NODE-VESION: 20
  BUILD_STATUS: "Build OK"

jobs:
  build:
    env:
      VAR_BUILD: "TEST"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE-VESION }}
      - name: Installation des dépendances
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: ./dist
          run: echo $BUILD_STATUS

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Télécharger l'artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./dist
      - name: Deploiement sur Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: ${{ github.event.sender.name }}
      - name: Affichage des variable
        run: |
          echo ${{ secrets.OUR_FIRST_TOKEN }}
          echo ${{ env.OUR_SECOND_VAR }}


